### ISSUE TITLE
Build ettikten sonra projenin run edilmesi

### ISSUE THREAD

**Issue by farukaydogan** [mesutpiskin/GenderClassification#1]
Hocam merhaba ben javada yeniyim projeyi başlatamadım. Aslında javada projeler nasıl derlenip çalıştırılır bulamadım çok araştırma yaptım ancak işe yarar bir sonuca ulaşamadım.
İntellij ile clone edip projeyi indiriyorum build ettikten sonra run butonu gelmiyor configuration istiyor bunu nasıl çözerim. Sizin kullandığınız herhangi bir yöntem veya  extension var mı teşekkürler.

**Comment by mesutpiskin** [comment]
Merhaba,
IDE ile main metodunu çalıştırabilirsiniz, UICamera.java dosyasına gidip main metodu üzerinden run edilebilir.

https://www.jetbrains.com/help/idea/running-applications.html#customizable-way

**Comment by farukaydogan** [comment]
Tesekkurler hocam sorun cozuldu. iyi calismalar dilerim.
